stages:
  make_dataset:
    cmd: >-
      poetry run python -m src.data.make_dataset
      llm-book/livedoor-news-corpus
      data/interim/dataset.parquet
      --mlflow_run_name=pipeline
    deps:
    - src/data/make_dataset.py
    outs:
    - data/interim/dataset.parquet

  build_token_list:
    cmd: >-
      poetry run python -m src.features.build_token_list
      data/interim/dataset.parquet
      data/interim/tokens.cloudpickle
      --mlflow_run_name=pipeline
    deps:
    - src/features/build_token_list.py
    - data/interim/dataset.parquet
    outs:
    - data/interim/tokens.cloudpickle

  train_word2vec:
    cmd: >-
      poetry run python -m src.models.train_w2v_model
      data/interim/tokens.cloudpickle
      models/Word2Vec/base_dict/w2v.bin
      models/Word2Vec/base_dict/kv.bin
    deps:
    - src/models/train_w2v_model.py
    - data/interim/tokens.cloudpickle
    outs:
    - models/Word2Vec/base_dict/w2v.bin
    - models/Word2Vec/base_dict/kv.bin

  build_sentences:
    cmd: >-
      poetry run python -m src.features.build_sentences
      data/interim/dataset.parquet
      data/interim/sentences.parquet
      --mlflow_run_name=pipeline
      --limit_sentence_size=${limit_sentence_size}
    deps:
    - src/features/build_sentences.py
    - data/interim/dataset.parquet
    outs:
    - data/interim/sentences.parquet

  embed_sentences:
    matrix:
      embedding_storategy: ${embedding_storategies}
      embedding_model_name: ${embedding_model_names}
      chunk_method: ${chunk_methods}
    cmd: >-
      poetry run python -m src.features.embed_sentences
      data/interim/sentences.parquet
      models/${item.embedding_storategy}/${item.embedding_model_name}/embeddings_${item.chunk_method}.cloudpickle
      --mlflow_run_name=pipeline
      --model_name_or_filepath=${item.embedding_model_name}
      --embedding_storategy=${item.embedding_storategy}
      --chunk_method=${item.chunk_method}
    deps:
    - src/features/embed_sentences.py
    - src/models/embedding/
    - src/models/search_engine/
    - data/interim/sentences.parquet
    - models/Word2Vec/base_dict/kv.bin
    outs:
    - models/${item.embedding_storategy}/${item.embedding_model_name}/embeddings_${item.chunk_method}.cloudpickle

  build_vector_db:
    matrix:
      embedding_storategy: ${embedding_storategies}
      embedding_model_name: ${embedding_model_names}
      chunk_method: ${chunk_methods}
    cmd: >-
      poetry run python -m src.features.build_vector_db
      data/interim/sentences.parquet
      models/${item.embedding_storategy}/${item.embedding_model_name}/embeddings_${item.chunk_method}.cloudpickle
      models/${item.embedding_storategy}/${item.embedding_model_name}/engine_${item.chunk_method}.cloudpickle
      --mlflow_run_name=pipeline
    deps:
    - src/features/build_vector_db.py
    - src/models/search_engine/
    - data/interim/sentences.parquet
    - models/${item.embedding_storategy}/${item.embedding_model_name}/embeddings_${item.chunk_method}.cloudpickle
    outs:
    - models/${item.embedding_storategy}/${item.embedding_model_name}/engine_${item.chunk_method}.cloudpickle

  recommend:
    matrix:
      embedding_storategy: ${embedding_storategies}
      embedding_model_name: ${embedding_model_names}
      chunk_method: ${chunk_methods}
    cmd: >-
      poetry run python -m src.models.recommend
      models/${item.embedding_storategy}/${item.embedding_model_name}/engine_${item.chunk_method}.cloudpickle
      --mlflow_run_name=pipeline
      --model_name_or_filepath=${item.embedding_model_name}
      --embedding_storategy=${item.embedding_storategy}
    deps:
    - src/models/recommend.py
    - src/models/embedding/
    - src/models/search_engine/
    - models/${item.embedding_storategy}/${item.embedding_model_name}/engine_${item.chunk_method}.cloudpickle

