stages:
  make_dataset:
    cmd: >-
      poetry run python -m src.data.make_dataset
      llm-book/livedoor-news-corpus
      data/interim/dataset.parquet
      --mlflow_run_name=pipeline
    deps:
    - src/data/make_dataset.py
    outs:
    - data/interim/dataset.parquet

  build_vectors:
    cmd: >-
      poetry run python -m src.features.build_features
      data/interim/dataset.parquet
      data/interim/vectors.cloudpickle
      --mlflow_run_name=pipeline
    deps:
    - src/features/build_features.py
    - data/interim/dataset.parquet
    outs:
    - data/interim/vectors.cloudpickle

  build_vector_db:
    cmd: >-
      poetry run python -m src.features.build_vector_db
      data/interim/vectors.cloudpickle
      data/interim/engine.cloudpickle
      --mlflow_run_name=pipeline
    deps:
    - src/features/build_vector_db.py
    - data/interim/vectors.cloudpickle
    outs:
    - data/interim/engine.cloudpickle
